### ISSUE TITLE
编译环境需求

### ISSUE THREAD

**Issue by git-printf** [xmtggh/VideoCalling#16]
搞了一周了，以前就没接触过安卓平台，这个我真的网上查了巨多的资料，用的android-studio编译，Android Gradle Plugin Version选择的3.2.0，Gradle Version选择的4.6，JDK选的1.8，构建是没问题了，ubuntu20.04的JAVA也改成java8了（原先是java11，无法使用gradlew build命令），gradlew还是会报错：
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.0/kotlin-stdlib-1.2.0.jar
Download https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar

> Task :app:lint FAILED
Ran lint on variant debug: 33 issues found
Ran lint on variant release: 33 issues found
Wrote HTML report to file:///home/wehuang/VideoCalling-master/app/build/reports/lint-results.html
Wrote XML report to file:///home/wehuang/VideoCalling-master/app/build/reports/lint-results.xml

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

**Comment by git-printf** [comment]
直接gradlew就行：）

**Comment by xmtggh** [comment]
你在app 的gradle里面加入上面提示的ndroid {
lintOptions {
abortOnError false
}
